#########################################################
# docker-compose情况下
# 不能共存host和端口映射
# tty & stdin_open是正常跑起来的关键 不然就不能独立出来ss-server进程
# 也不能正常输出log
# 一旦做映射 必定是用了bridge
# 想要避免使用docker-pr 必须用host
#########################################################
version: '3.5'
services:
  ss-normal:
    image: edisonleeeee/ss-base:latest
    restart: always
    stdin_open: true
    tty: true
    network_mode: host
    volumes:
      - '$PWD/conf-group-34498.json:/etc/shadowsocks-libev/conf-group-34498.json'
    command: ss-manager --manager-address /var/run/shadowsocks-manager.sock -c /etc/shadowsocks-libev/conf-group-34498.json
  ss-obfs:
    image: edisonleeeee/ss-base:latest
    restart: always
    network: host
    ports:
      - "10728:10728"
      - "10738:10738"
    volumes:
      - '$PWD:/etc/shadowsocks-libev/:ro'
    command: /bin/sh -c ss-manager --manager-address /var/run/shadowsocks-manager.sock -c /etc/shadowsocks-libev/conf-obfs.json